[regions]
maincpu = 0
tc0100scn_1 = 1
sprites = 2
audiocpu = 3
"ymsnd:adpcma" = 4
"ymsnd:adpcmb" = 5

[machines]
finalb = "00 00"
dondokod = "01 00"
megab = "02 00"
thundfox = "03 00"
cameltry = "04 00"
qtorimon = "05 00"
liquidk = "06 00"
quizhq = "07 00"
ssi = "08 00"
gunfront = "09 00"
growl = "0a 00"
mjnquest = "0b 00"
footchmp = "0d 00"
koshien = "0d 00"
yuyugogo = "0e 00"
ninjak = "0f 00"
solfigtr = "10 00"
qzquest = "11 00"
pulirula = "12 00"
metalb = "13 00"
qzchikyu = "14 00"
yesnoj = "15 00"
deadconx = "16 00"
dinorex = "17 00"
qjinsei = "18 00"
qcrayon = "19 00"
qcrayon2 = "1a 00"

[buttons]
default.snes = "B,A,X,Y,Start,Select"
default.game = "Btn1,Btn2,Btn3,Btn4,Start,Coin"
finalb = { snes = "B,A,X,Start,Select", game = "Btn1,Btn2,Btn2,-,Start,Coin" }

[metadata]
default.mameversion = 245

