[regions]
maincpu.id = 0
tc0100scn_1.id = 1
sprites.id = 2
sprites.swap = true
audiocpu.id = 3
"ymsnd:adpcma" = { id = 4 }
"ymsnd:adpcmb" = { id = 5 }
tc0430grw = 6
tc0280grd = 6
tc0430scp = 7

[machines]
finalb = "00 00"
dondokod = "01 00"
megablst = "02 00"
#thundfox = "03 00"
cameltry = "04 00"
#qtorimon = "05 00"
liquidk = "06 00"
#quizhq = "07 00"
ssi = "08 00"
gunfront = "09 00"
growl = "0a 00"
#mjnquest = "0b 00"
#footchmp = "0d 00"
#koshien = "0d 00"
#yuyugogo = "0e 00"
#ninjak = "0f 00"
solfigtr = "10 00"
#qzquest = "11 00"
#pulirula = "12 00"
#metalb = "13 00"
#qzchikyu = "14 00"
#yesnoj = "15 00"
#deadconx = "16 00"
dinorex = "17 00"
#qjinsei = "18 00"
#qcrayon = "19 00"
#qcrayon2 = "1a 00"
driftout = "1b 00"

[buttons]
default.snes = "B,A,X,Y,Start,Select"
default.game = "Btn1,Btn2,Btn3,Btn4,-,-,Start,Coin,Pause,SS"
finalb = { snes = "B,A,X,Start,Select", game = "Punch A,Punch B,Duck,-,-,-,Start,Coin,Pause,SS" }
dondokod = { snes = "B,A,Start,Select", game = "Attack,Jump,-,-,-,-,Start,Coin,Pause,SS" }
cameltry = { snes = "B,Start,Select", game = "Shake,-,-,-,-,-,Start,Coin,Pause,SS" }
liquidk = { snes = "B,A,Start,Select", game = "Attack,Jump,-,-,-,-,Start,Coin,Pause,SS" }
ssi = { snes = "B,A,Start,Select", game = "Shoot,Use Item,-,-,-,-,Start,Coin,Pause,SS" }
gunfront = { snes = "B,A,Start,Select", game = "Shoot,Bomb,-,-,-,-,Start,Coin,Pause,SS" }
growl = { snes = "B,A,Start,Select", game = "Attack,Jump,-,-,-,-,Start,Coin,Pause,SS" }
dinorex = { snes = "B,A,Start,Select", game = "Bite/Punch,Kick,-,-,-,-,Start,Coin,Pause,SS" }
solfigtr = { snes = "B,A,X,Start,Select", game = "Punch,Kick,Jump,-,-,-,Start,Coin,Pause,SS" }
driftout = { snes = "B,A,Start,Select", game = "Accelerator,Brake,-,-,-,-,Start,Coin,Pause,SS" }


[pretty_names]
# Pretty machine names for directory organization
# Used for _alternatives/_<PRETTY_NAME>/ subdirectories
# Only parent machines need to be defined here
cameltry = "Cameltry"
dinorex = "Dino Rex"
dondokod = "Don Doko Don"
driftout = "Drift Out"
finalb = "Final Blow"
growl = "Growl"
gunfront = "Gun Frontier"
liquidk = "Liquid Kids"
megablst = "Mega Blast"
solfigtr = "Solitary Fighter"
ssi = "Super Space Invaders '91"

[abbreviations]
# Dip switch name abbreviations (24 character limit)
"Number of Enemies 1/2 Player" = "Enemies 1P/2P"
"Price to Continue" = "Continue Price"
"Game Over Type" = "Game Over"
"2 Players Mode" = "2P Mode"

# Dip switch value abbreviations (24 character limit)
"MTX2 (4 players / 2 cabinets combined)" = "MTX2 4P/2C"
"4 Players / 2 cabinets combined" = "4P/2 cabs"
"TROG (4 players / 2 coin slots)" = "TROG 4P/2C"
"TMNT (4 players / 4 coin slots)" = "TMNT 4P/4C"
"Losing Team's Game is Over" = "Losing Team"
"4 Players / 4 Coin Slots" = "4P/4 Coins"
"4 Players / 2 Coin Slots" = "4P/2 Coins"
"3 Coins/1 Credit" = "3C/1C"
"2 Coins/1 Credit" = "2C/1C"
"1 Coin/1 Credit" = "1C/1C"
"Same as Start" = "Same"
"Both Teams' Games Over" = "Both Teams Over"
"10k and every 80k" = "10k+80k"
"20k and every 80k" = "20k+80k"
"30k and every 80k" = "30k+80k"
"60k and every 80k" = "60k+80k"
"80k and every 160k" = "80k+160k"
"70k and every 150k" = "70k+150k"
"100k and every 200k" = "100k+200k"
"50k and every 120k" = "50k+120k"
"Simultaneous" = "Simultaneous"
"Alternate, Single" = "Alt Single"
"Alternate, Dual" = "Alt Dual"
"Not Allowed" = "Not Allowed"

[metadata]
default.mameversion = 277

